### ISSUE TITLE
Have weights available 

### ISSUE THREAD

**Issue by merveenoyan** [xinghaochen/TinySAM#1]
Hello 👋  Thanks a lot for open-sourcing the code!
I wanted to try TinySAM and in the demo and README there seems to be a weights folder which I couldn't find. 

In any case, would you like to have the weights available on Hugging Face Hub and load them from there?

**Comment by xinghaochen** [comment]
Checkpoint is released in https://github.com/xinghaochen/TinySAM/releases/download/1.0/tinysam.pth

Thanks for the suggestion and we may upload the weights to huggingface later.

**Comment by merveenoyan** [comment]
Hello @xinghaochen I've uploaded model weights and built a demo:
https://huggingface.co/spaces/merve/tinysam
https://huggingface.co/merve/tinysam
Would you like to add this to README so people can try easily?

**Comment by xinghaochen** [comment]
Thanks for the awesome demo! 
I have just added the link to your Hugging Face demo in README.

**Comment by merveenoyan** [comment]
@xinghaochen do you (or your lab/organization) have a hugging face account? We can move the repositories under your namespace if so.

**Comment by xinghaochen** [comment]
> @xinghaochen do you (or your lab/organization) have a hugging face account? We can move the repositories under your namespace if so.

https://huggingface.co/xinghaochen

**Comment by merveenoyan** [comment]
@xinghaochen we noticed there's an organization for Huawei Noah's Ark Lab: https://huggingface.co/huawei-noah you can join there and move the models and demo there if it works for you (we moved all of them under your workspace, you can directly go to repository settings and you'll find the option to move it to the organization once you become a member of the org)
