### ISSUE TITLE
Why is the mask a three-channel image? How do I export Onnx files?

### ISSUE THREAD

**Issue by duxuan11** [xinghaochen/TinySAM#10]
I don't know what you changed about the original SAM, but when mask is used as output, it has three channels instead of one. And use max score to select.

**Comment by shuh15** [comment]
yes, we adopt multi-output mode to train the network, which means the number of output masks is 3,  among which we select the one with max score as the final output mask. As for exporting onnx files, [samexporter](https://github.com/vietanhdev/samexporter/) would be helpful.
