### ISSUE TITLE
run apk demo

### ISSUE THREAD

**Issue by duckzhao** [xinghaochen/TinySAM#11]
Thank you for your useful work.
And I noticed that there is a apk demo in your README, how can I get it?
![Snipaste_2024-01-02_21-10-58](https://github.com/xinghaochen/TinySAM/assets/52394358/4fde52b2-63dd-485b-aead-ae10e5d97b59)
If the apk demo is not open source, could you tell me what deployment method to use? like NCNN, MNN.
Looking forward to your reply!

**Comment by xinghaochen** [comment]
Currently we just develop a simple and naive android demo to run our TinySAM, following https://pytorch.org/mobile/android/.
We may release the apk when we further improve the android demo.
