### ISSUE TITLE
为什么量化模型的体积更大，推理速度更慢？

### ISSUE THREAD

**Issue by RovingYoung** [xinghaochen/TinySAM#15]
如题，使用设备为3060，对比相同输入的模型与量化模型，量化模型体积更大，推理速度更慢

**Comment by xinghaochen** [comment]
你好，当前量化的模型是插入了一些量化算子后的Pytorch pth格式Checkpoint。需要进一步简化模型，比如转成onnx之后才能获得加速和模型大小下降。

**Comment by RovingYoung** [comment]
> 你好，当前量化的模型是插入了一些量化算子后的Pytorch pth格式Checkpoint。需要进一步简化模型，比如转成onnx之后才能获得加速和模型大小下降。

明白了，感谢您的解答
