### ISSUE TITLE
demo_hierachical_everything.py Produces No Masks

### ISSUE THREAD

**Issue by jfischoff** [xinghaochen/TinySAM#2]
I can't the demo_hierachical_everything to work. There are no errors but the output from `hierarchical_generate` is an empty list.

Here is the image it makes:
![test_everthing](https://github.com/xinghaochen/TinySAM/assets/168507/fbb78918-ec21-4ba4-8364-9c9722aac2ad)

Env
- python 3.9
- pip install torch==1.10.2 torchvision==0.11.3 matplotlib>=3.5.1 opencv-python==4.8.1.78 timm==0.9.12

**Comment by xinghaochen** [comment]
Sorry for the minor bug in the previous codes and we have just updated the repo. I think it works right now:

![image](https://github.com/xinghaochen/TinySAM/assets/7226525/64aa1c8c-4488-4d76-9026-d1c5badf7e2c)

**Comment by jfischoff** [comment]
Awesome! I'll take a look.
