### ISSUE TITLE
Questions about latency

### ISSUE THREAD

**Issue by Greywan** [xinghaochen/TinySAM#20]
![2024-03-05_16-03](https://github.com/xinghaochen/TinySAM/assets/61035902/3aad3831-f32c-4863-957f-5cf30e960a67)

I have a question, does this time represent the runtime of a single image in SegEvery mode?

**Comment by xinghaochen** [comment]
Yes, the Time(s) in this table is the latancy of everything mode.

**Comment by Greywan** [comment]
> Yes, the Time(s) in this table is the latancy of everything mode.

Thank you for your reply.
