### ISSUE TITLE
export the QTinySAM onnx file

### ISSUE THREAD

**Issue by duxuan11** [xinghaochen/TinySAM#21]
![image](https://github.com/xinghaochen/TinySAM/assets/64136561/0e6f4646-c93e-470c-8b2d-66c7c0de635a)
I want to export QTinySAM onnx file, but I  met this question. Do you have a solution?

**Comment by shuh15** [comment]
Hi, We didn't try to export quantization model with "quantization_layer/layers.py". The possible solution is to set parameters(such as w_interval)  for all quantization layers by using 'get_parameter()' before 'torch.onnx.export()'.

**Comment by GuangxianZhu** [comment]
![image](https://github.com/xinghaochen/TinySAM/assets/62783839/96742807-fe1d-491f-9019-37176ce308c8)
Thank you for your work! I am trying to export the Q-model to ONNX format. but seems it won't work, do you have any suggestions?

**Comment by Mon-amour** [comment]
> ![image](https://private-user-images.githubusercontent.com/64136561/316942598-0e6f4646-c93e-470c-8b2d-66c7c0de635a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NTkzMzEsIm5iZiI6MTcyMTk1OTAzMSwicGF0aCI6Ii82NDEzNjU2MS8zMTY5NDI1OTgtMGU2ZjQ2NDYtYzkzZS00NzBjLThiMmQtNjZjN2MwZGU2MzVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDAxNTcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkYjlkNDYzNjRhYzg5ZjhjYzVkYjVhYjIzY2NmNDgzMTQ2YmViNjI5NTkzYTBmNTkzNTU0NjBiNDVmNWZkNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fxPHGY3oHcQz5-qEEl0M-x6PBpibXDDztpuXAXd3Lgc) I want to export QTinySAM onnx file, but I met this question. Do you have a solution?
Have you solved the problem? Did you export QtinySAM onnx file successfully? I met the same problem as you when exporting QtinySAM.

**Comment by duxuan11** [comment]
> > ![image](https://private-user-images.githubusercontent.com/64136561/316942598-0e6f4646-c93e-470c-8b2d-66c7c0de635a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NTkzMzEsIm5iZiI6MTcyMTk1OTAzMSwicGF0aCI6Ii82NDEzNjU2MS8zMTY5NDI1OTgtMGU2ZjQ2NDYtYzkzZS00NzBjLThiMmQtNjZjN2MwZGU2MzVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDAxNTcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkYjlkNDYzNjRhYzg5ZjhjYzVkYjVhYjIzY2NmNDgzMTQ2YmViNjI5NTkzYTBmNTkzNTU0NjBiNDVmNWZkNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fxPHGY3oHcQz5-qEEl0M-x6PBpibXDDztpuXAXd3Lgc) I want to export QTinySAM onnx file, but I met this question. Do you have a solution?
> > Have you solved the problem? Did you export QtinySAM onnx file successfully? I met the same problem as you when exporting QtinySAM.
Don't try to export QTinysam onnx , it's so complexity, just export tinysam onnx.

**Comment by Mon-amour** [comment]
Thanks for your reply.
