### ISSUE TITLE
Tiny-Sam vs HQ-Sam

### ISSUE THREAD

**Issue by Meteplus** [xinghaochen/TinySAM#4]
with four points, the tiny-sam does'nt segment correctly,while HQ-Sam works well  even for pictures with great noises
![test](https://github.com/xinghaochen/TinySAM/assets/50652630/43e6995e-930e-44b6-8a3c-b1ce83004932)
![20231226114538](https://github.com/xinghaochen/TinySAM/assets/50652630/ddac07ac-c1f2-4f6a-8710-135071f613ce)

**Comment by xinghaochen** [comment]
Could you provide the original input image so that we could perform further analysis? Thanks.

**Comment by Meteplus** [comment]
give me your email address. I can send you my test images

**Comment by Meteplus** [comment]
![as](https://github.com/xinghaochen/TinySAM/assets/50652630/b5b90f7e-c174-45a7-a34e-01ec4a10996e)
![cup3(1)](https://github.com/xinghaochen/TinySAM/assets/50652630/7a7ff8ea-2c4a-46a7-9be5-14ed7f68152f)
![20231108224848](https://github.com/xinghaochen/TinySAM/assets/50652630/9c3e56ac-c4cb-4e53-8fdd-4fdad91f44e6)
![alise](https://github.com/xinghaochen/TinySAM/assets/50652630/beaaf09f-24fe-4789-8840-d59674855002)
![lagou](https://github.com/xinghaochen/TinySAM/assets/50652630/e26ae789-705a-4bc9-885f-5609a5784e6f)

maybe you can analyze through these input images

**Comment by xinghaochen** [comment]
Thanks for your test images.

- I notice that the areas around the given prompt points are quite similar to that of background, i.e., both are in white, which make the segmentation of such mask quite difficult. Segmenting the main area of the image by TinySAM obtains reasonable results:
![image](https://github.com/xinghaochen/TinySAM/assets/7226525/eeb1e5d3-1a84-45fe-b729-442de37c0ce1)
- You can also provide additional negative prompt points to obtain the following result:
```
input_point = np.array([[1300, 100], [200, 300], [2400, 300], [1300, 1100], [100, 100], [2500, 1200]])
input_label = np.array([1, 1, 1, 1, 0, 0])
```
![image](https://github.com/xinghaochen/TinySAM/assets/7226525/ee0be0d7-0741-41f3-82c2-04d3a7cf0403)
- Your above results of HQ-SAM are obtained with a relative large model, i.e., ViT-L backbone, which is much larger than TinySAM. The [Light HQ-SAM](https://github.com/SysCV/sam-hq?tab=readme-ov-file#model-checkpoints) obtains the following result:
![image](https://github.com/xinghaochen/TinySAM/assets/7226525/a852ea6f-c9dc-419c-b47d-415c4a917744)

**Comment by Meteplus** [comment]
yes,i've got better results with negative points,thank you for your reply
